version: '3'


services:
  api:
    image: system-api-test
    container_name: system-api-test
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
      - storage
    environment:
      DB_URI: postgresql://postgres:postgres@db-system-test:5432/test
      NODE_ENV: development
      SECRET_KEY: secret
      CORS_ORIGIN_WHITELIST: https://localhost:8080
      REDIS_URL: redis://redis-cache

  db:
    container_name: db-system-test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  storage:
    image: redis
    container_name: redis-cache
    command: [ "redis-server" ]
    ports:
      - "6379:6379"
